In [1]:
import pandas as pd

doc = pd.read_csv('dataset.csv')

In [5]:
doc.head(10)

        ID_Pedido Data_Pedido ID_Cliente  ...                                       Nome_Produto Valor_Venda Quantidade
0  CA-2016-152156  2016-11-08   CG-12520  ...                  Bush Somerset Collection Bookcase    261.9600        NaN
1  CA-2016-152156  2016-11-08   CG-12520  ...  Hon Deluxe Fabric Upholstered Stacking Chairs,...    731.9400        NaN
2  CA-2016-138688  2016-06-12   DV-13045  ...  Self-Adhesive Address Labels for Typewriters b...     14.6200        2.0
3  US-2015-108966  2015-10-11   SO-20335  ...      Bretford CR4500 Series Slim Rectangular Table    957.5775        5.0
4  US-2015-108966  2015-10-11   SO-20335  ...                     Eldon Fold 'N Roll Cart System     22.3680        2.0
5  CA-2014-115812  2014-06-09   BH-11710  ...  Eldon Expressions Wood and Plastic Desk Access...     48.8600        7.0
6  CA-2014-115812  2014-06-09   BH-11710  ...                                         Newell 322      7.2800        4.0
7  CA-2014-115812  2014-06-09   BH-11710  ...                     Mitel 5320 IP Phone VoIP phone    907.1520        6.0
8  CA-2014-115812  2014-06-09   BH-11710  ...  DXL Angle-View Binders with Locking Rings by S...     18.5040        3.0
9  CA-2014-115812  2014-06-09   BH-11710  ...                   Belkin F5C206VTEL 6 Outlet Surge    114.9000        5.0

[10 rows x 11 columns]

In [3]:
#Filtrando o dataframe pela coluna segmento com valores que iniciam com as letras 'Con'

doc[doc.Segmento.str.startswith('Con')].head()

        ID_Pedido Data_Pedido ID_Cliente  ...                                       Nome_Produto Valor_Venda Quantidade
0  CA-2016-152156  2016-11-08   CG-12520  ...                  Bush Somerset Collection Bookcase    261.9600        NaN
1  CA-2016-152156  2016-11-08   CG-12520  ...  Hon Deluxe Fabric Upholstered Stacking Chairs,...    731.9400        NaN
3  US-2015-108966  2015-10-11   SO-20335  ...      Bretford CR4500 Series Slim Rectangular Table    957.5775        5.0
4  US-2015-108966  2015-10-11   SO-20335  ...                     Eldon Fold 'N Roll Cart System     22.3680        2.0
5  CA-2014-115812  2014-06-09   BH-11710  ...  Eldon Expressions Wood and Plastic Desk Access...     48.8600        7.0

[5 rows x 11 columns]

In [8]:
#Filtrando dataframe pela coluna Segmento com valores que terminam com as letras 'mer'

doc[doc.Segmento.str.endswith('mer')].head()

        ID_Pedido Data_Pedido ID_Cliente  ...                                       Nome_Produto Valor_Venda Quantidade
0  CA-2016-152156  2016-11-08   CG-12520  ...                  Bush Somerset Collection Bookcase    261.9600        NaN
1  CA-2016-152156  2016-11-08   CG-12520  ...  Hon Deluxe Fabric Upholstered Stacking Chairs,...    731.9400        NaN
3  US-2015-108966  2015-10-11   SO-20335  ...      Bretford CR4500 Series Slim Rectangular Table    957.5775        5.0
4  US-2015-108966  2015-10-11   SO-20335  ...                     Eldon Fold 'N Roll Cart System     22.3680        2.0
5  CA-2014-115812  2014-06-09   BH-11710  ...  Eldon Expressions Wood and Plastic Desk Access...     48.8600        7.0

[5 rows x 11 columns]

As funções STARTSWITH() e ENDSWITH() são muito úteis quando for necessário filtrar strings por caracteres que apareçam no começo e/ou final.

In [10]:
doc.Segmento.value_counts() # para mostrar oq há em segmetos

Consumer       5191
Corporate      3020
Home Office    1783
Name: Segmento, dtype: int64

In [13]:
#Split de string com data frame 

doc['ID_Pedido'].head() #formato dos dados de id pedido

0    CA-2016-152156
1    CA-2016-152156
2    CA-2016-138688
3    US-2015-108966
4    US-2015-108966
Name: ID_Pedido, dtype: object

In [15]:
#split coluna pelo caracter ['-']

doc['ID_Pedido'].str.split('-')

0       [CA, 2016, 152156]
1       [CA, 2016, 152156]
2       [CA, 2016, 138688]
3       [US, 2015, 108966]
4       [US, 2015, 108966]
               ...
9989    [CA, 2014, 110422]
9990    [CA, 2017, 121258]
9991    [CA, 2017, 121258]
9992    [CA, 2017, 121258]
9993    [CA, 2017, 119914]
Name: ID_Pedido, Length: 9994, dtype: object

O resultado da celula acima mostra que foi divido em várias listas para extrair o ano precisamos especifcar a posição do indice da informação que vai ser extraida, no caso o ano

In [16]:
doc['ID_Pedido'].str.split('-').str[1].head()

0    2016
1    2016
2    2016
3    2015
4    2015
Name: ID_Pedido, dtype: object

In [17]:
#criando uma nova coluna com a informação extraida
doc['Ano'] = doc['ID_Pedido'].str.split('-').str[1]

In [18]:
doc.head()

        ID_Pedido Data_Pedido ID_Cliente  ... Valor_Venda Quantidade   Ano
0  CA-2016-152156  2016-11-08   CG-12520  ...    261.9600        NaN  2016
1  CA-2016-152156  2016-11-08   CG-12520  ...    731.9400        NaN  2016
2  CA-2016-138688  2016-06-12   DV-13045  ...     14.6200        2.0  2016
3  US-2015-108966  2015-10-11   SO-20335  ...    957.5775        5.0  2015
4  US-2015-108966  2015-10-11   SO-20335  ...     22.3680        2.0  2015

[5 rows x 12 columns]

In [19]:
#STRIP que remove caracteres da string

doc['Data_Pedido']

0       2016-11-08
1       2016-11-08
2       2016-06-12
3       2015-10-11
4       2015-10-11
           ...
9989    2014-01-21
9990    2017-02-26
9991    2017-02-26
9992    2017-02-26
9993    2017-05-04
Name: Data_Pedido, Length: 9994, dtype: object

In [28]:
doc['Data_Pedido'] = doc['Data_Pedido'].str.strip('20')

In [29]:
doc.head()

        ID_Pedido Data_Pedido ID_Cliente  ... Valor_Venda Quantidade   Ano
0  CA-2016-152156    16-11-08   AX-12520  ...    261.9600        NaN  2016
1  CA-2016-152156    16-11-08   AX-12520  ...    731.9400        NaN  2016
2  CA-2016-138688     16-06-1   DV-13045  ...     14.6200        2.0  2016
3  US-2015-108966    15-10-11   SO-20335  ...    957.5775        5.0  2015
4  US-2015-108966    15-10-11   SO-20335  ...     22.3680        2.0  2015

[5 rows x 12 columns]

In [30]:
#SUBSTINTUINDO CARACTERES 

doc['ID_Cliente'] = doc['ID_Cliente'].str.replace('CG','AX')

In [31]:
doc.head()

        ID_Pedido Data_Pedido ID_Cliente  ... Valor_Venda Quantidade   Ano
0  CA-2016-152156    16-11-08   AX-12520  ...    261.9600        NaN  2016
1  CA-2016-152156    16-11-08   AX-12520  ...    731.9400        NaN  2016
2  CA-2016-138688     16-06-1   DV-13045  ...     14.6200        2.0  2016
3  US-2015-108966    15-10-11   SO-20335  ...    957.5775        5.0  2015
4  US-2015-108966    15-10-11   SO-20335  ...     22.3680        2.0  2015

[5 rows x 12 columns]

In [32]:
#COMBINAÇÃO DE STRING

doc['Pedido_Segmento'] = doc['ID_Pedido'].str.cat(doc['Segmento'], sep='-')
doc.head()

        ID_Pedido Data_Pedido ID_Cliente   Segmento  ... Valor_Venda Quantidade   Ano           Pedido_Segmento
0  CA-2016-152156    16-11-08   AX-12520   Consumer  ...    261.9600        NaN  2016   CA-2016-152156-Consumer
1  CA-2016-152156    16-11-08   AX-12520   Consumer  ...    731.9400        NaN  2016   CA-2016-152156-Consumer
2  CA-2016-138688     16-06-1   DV-13045  Corporate  ...     14.6200        2.0  2016  CA-2016-138688-Corporate
3  US-2015-108966    15-10-11   SO-20335   Consumer  ...    957.5775        5.0  2015   US-2015-108966-Consumer
4  US-2015-108966    15-10-11   SO-20335   Consumer  ...     22.3680        2.0  2015   US-2015-108966-Consumer

[5 rows x 13 columns]